name: Parse Frontmatter

on:
  push:
    paths:
      - 'posts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml json

    - name: Run parsing script
      run: python .github/scripts/index_posts.py
